### ISSUE TITLE
user_dic문의

### ISSUE THREAD

**Issue by parksanha** [shineware/RKOMORAN#12]
안녕하세요.

아래와 같이 user_dic을 설정하고 사용하려고 하는데 작동하지 않습니다.

어떻게 해결하면 좋을까요?
![유저](https://user-images.githubusercontent.com/62294108/80187060-f9ce4180-8649-11ea-9ec6-2daff6807ee5.png)

**Comment by dolpang2** [comment]
@parksanha 안녕하세요. 혹시 user_dictionary.txt의 경로가 현재 R 파일과 동일 경로에 있는지와 파일 Encoding을 확인해주실 수 있을까요?

**Comment by parksanha** [comment]
@dolpang2 
경로는 setwd()로 설정을 해주었고, R과 동일 경로에 지정을 해두어도 안됩니다.

파일 인코딩은 UTF-8로 했습니다.

**Comment by parksanha** [comment]
@dolpang2 방금 인코딩을 ANSI으로 변경했더니 되네요!!!!! 감사합니다. ㅎ

**Comment by dolpang2** [comment]
@parksanha 우선 해결되었다고 하시니 다행이네요. 다음 릴리즈 때는 기본 인코딩을 UTF-8로 강제하는 패치를 적용해야겠네요. 감사합니다. 이슈는 클로즈하겠습니다
